spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/opentransport_db
spring.datasource.username=root
spring.datasource.password=LoopDesa22
spring.jpa.hibernate.ddl-auto=update