spring.datasource.url=jdbc:postgresql://localhost:5432/opentransporte
spring.datasource.username=admin
spring.datasource.password=13788fff-3acb-35f9-bd1b-ba1b46591k2f
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true